#
# $Id: Makefile,v 1.2 2010/05/25 00:00:00 root Exp $
#

G++     = $(ROOTFS)/host/bin/mipsel-linux-g++
AR      = $(ROOTFS)/host/bin/mipsel-linux-ar
CFLAGS  = -Wall -mips32r2 -mtune=24kf -O2 -funroll-loops -fomit-frame-pointer
SRC	= libtta.cpp
LIB	= libtta++

all:	$(SRC)
	$(G++) -c $(CFLAGS) $(SRC) -o $(LIB).o
	$(AR) rcs $(LIB).a $(LIB).o

clean:
	rm -f *.o *.lo *.a

